#!/bin/bash
#Simple password generator using base64

echo "THIS IS A PASSWORD GENERATOR"
echo "Enter the legth of password you wish to create"

read PASS_LENGTH

for p in $(seq 1 10);#sequence from 1 -10
do
	openssl rand -base64 48 | cut -c1-$PASS_LENGTH
done 
